[workspace]
members = [
    "snark-verifier",
    "snark-verifier-sdk"
]
resolver = "2"

[patch.'https://github.com/zkonduit/halo2']
halo2_proofs = { git = "https://github.com/Lagrange-Labs/halo2", rev = "38abade" }

